### ISSUE TITLE
Strip "҉" character

### ISSUE THREAD

**Issue by bennycode** [mathiasbynens/strip-combining-marks#1]
I tested the library with the following Zalgo text:

```js
var crazyOnes = "ĉ̣̜̱͚͔̘̗̋ͭͥ̋r̥̗͊̀ͨ̾͋̾ͤa̤̜̟͓̣̗͋͊͜ẓ̪̳̤̯̩y͂́ ̅̀̈́͂҉̙̳̠̦̗̣ǫ̘̠͚͎̲͉ͩͪ͆̔n̝ͣͪ̍ͦ̋͋ͣe̟̳̙̙̺̲͝s̠̖͇̺̞̤";
stripCombiningMarks(crazyOnes); // "crazy ҉ones"
```

So it looks like that the character ` ҉` doesn't get stripped. 😢 

But it should be stripped because it ruins the text rendering.

**Screenshot:**

![capture](https://cloud.githubusercontent.com/assets/469989/23912186/39bed17e-08df-11e7-9dba-0cff9502e3bd.PNG)

**Comment by mathiasbynens** [comment]
That symbol is U+0489 COMBINING CYRILLIC MILLIONS SIGN which has `Line_Break=Combining_Mark`. Currently we’re only including symbols with `Block=Combining*`.

**Comment by bennycode** [comment]
Ok, thanks for clarification and publishing v1.0. 👍
